import streamlit as st
import matplotlib.pyplot as plt

st.set_page_config(page_title="How would your state look like?")

####### functions
def check_if_everything_selected():
    for question_dict in questions:
        for category, question in question_dict.items():
            response = st.session_state.get(f'{question}_response')
            if response == 'Choose':
                return False
    return True

def calculate_scores():
    user_responses_economic_policy, user_responses_governance_policy = 0, 0
    for question_dict in questions:
        category = question_dict.get("category")
        question = question_dict.get("question")
        if category == 0:
            response = st.session_state.get(f'{question}_response')
            responses = question_dict.get("responses")
            user_responses_economic_policy += responses.get(response)
        elif category == 1:
            response = st.session_state.get(f'{question}_response')
            responses = question_dict.get("responses")
            user_responses_governance_policy += responses.get(response)
    return user_responses_economic_policy, user_responses_governance_policy

####### streamlit 
st.markdown('# How would your state look like?')

st.markdown("""
do you know this popular thiel question - "how would you build a state if you started from scratch?" this is obviously a difficult question, but it's fascinating and fundamental. below you can find 40 questions. if you answer them, they get plotted and as a result, you can see how the state you would build is politically oriented.

each question pertains to either the topic of economic policy or governance policy. the split is 20/20. there are 5 options to choose from for every question. in the backend, each option is represented by a number. this results in the end in having two numbers - one which represents the economic policy and another for the governance policy. these two numbers are plotted against each other. economic policy lies on the x-axis ranging from communism to capitalism and the y-axis, which represents governance policy, ranges from autocracy to democracy.

questions are generated by gpt4. the temperature setting was one. the initial two prompts for the project were the following:

me: "do you know the political compass test https://www.politicalcompass.org/test/en?"

me: "i want to create my own test which i want to call "how does your state look like?". it should basically be a test that asks questions about how a person would design their own state. in the end, based on the answers, a plot is created showing the spectrum of where a person would be located. do you think it would be possible to create such a test?"

based on a follow up question, the questions were generated. the test, like most sociological tests, is only an approximation and should therefore be viewed with caution.
""")

questions = [
    {
        "category": 0,
        "question": "Should the state control major industries?",
        "responses": {
            "Strongly Agree": -2,
            "Agree": -1,
            "Neutral": 0,
            "Disagree": 1,
            "Strongly Disagree": 2
        }
    },
    {
        "category": 1,
        "question": "Should the state have the power to control media outlets?",
        "responses": {
            "Strongly Agree": -2,
            "Agree": -1,
            "Neutral": 0,
            "Disagree": 1,
            "Strongly Disagree": 2
        }
    },
    {
        "category": 0,
        "question": "Should the state provide a universal basic income?",
        "responses": {
            "Strongly Agree": -2,
            "Agree": -1,
            "Neutral": 0,
            "Disagree": 1,
            "Strongly Disagree": 2
        }
    },
    {
        "category": 1,
        "question": "Should the state be able to restrict individual freedoms for the sake of national security?",
        "responses": {
            "Strongly Agree": -2,
            "Agree": -1,
            "Neutral": 0,
            "Disagree": 1,
            "Strongly Disagree": 2
        }
    },
    {
        "category": 0,
        "question": "Should businesses be allowed to operate with minimal state interference?",
        "responses": {
            "Strongly Agree": 2,
            "Agree": 1,
            "Neutral": 0,
            "Disagree": -1,
            "Strongly Disagree": -2
        }
    },
    {
        "category": 1,
        "question": "Should citizens be able to vote directly on all major national decisions?",
        "responses": {
            "Strongly Agree": 2,
            "Agree": 1,
            "Neutral": 0,
            "Disagree": -1,
            "Strongly Disagree": -2
        }
    },
    {
        "category": 0,
        "question": "Should the state play a minimal role in wealth redistribution?",
        "responses": {
            "Strongly Agree": 2,
            "Agree": 1,
            "Neutral": 0,
            "Disagree": -1,
            "Strongly Disagree": -2
        }
    }, 
    {
        "category": 1,
        "question": "Should the state be as transparent as possible, sharing all non-security related information with the public?",
        "responses": {
            "Strongly Agree": 2,
            "Agree": 1,
            "Neutral": 0,
            "Disagree": -1,
            "Strongly Disagree": -2
        }
    },
    {
        "category": 0,
        "question": "Should the state provide free healthcare for all citizens?",
        "responses": {
            "Strongly Agree": -2,
            "Agree": -1,
            "Neutral": 0,
            "Disagree": 1,
            "Strongly Disagree": 2
        }
    }, 
    {
        "category": 1,
        "question": "Should the state enforce strict laws and penalties to maintain social order?",
        "responses": {
            "Strongly Agree": -2,
            "Agree": -1,
            "Neutral": 0,
            "Disagree": 1,
            "Strongly Disagree": 2
        }
    },
    {
        "category": 0,
        "question": "Should the state subsidize education at all levels, making it free for all?",
        "responses": {
            "Strongly Agree": -2,
            "Agree": -1,
            "Neutral": 0,
            "Disagree": 1,
            "Strongly Disagree": 2
        }
    },
    {
        "category": 1,
        "question": "Should the state provide a platform for citizens to participate in policy-making?",
        "responses": {
            "Strongly Agree": 2,
            "Agree": 1,
            "Neutral": 0,
            "Disagree": -1,
            "Strongly Disagree": -2
        }
    },
    {
        "category": 0,
        "question": "Should the state regulate prices of essential goods and services?",
        "responses": {
            "Strongly Agree": -2,
            "Agree": -1,
            "Neutral": 0,
            "Disagree": 1,
            "Strongly Disagree": 2
        }
    },
    {
        "category": 1,
        "question": "Should the state's power be decentralized, giving more authority to local governments?",
        "responses": {
            "Strongly Agree": 2,
            "Agree": 1,
            "Neutral": 0,
            "Disagree": -1,
            "Strongly Disagree": -2
        }
    },
    {
        "category": 0,
        "question": "Should the state provide financial support to startups and small businesses?",
        "responses": {
            "Strongly Agree": -2,
            "Agree": -1,
            "Neutral": 0,
            "Disagree": 1,
            "Strongly Disagree": 2
        }
    },
    {
        "category": 1,
        "question": "Should the state ensure equal representation of all groups in government bodies?",
        "responses": {
            "Strongly Agree": 2,
            "Agree": 1,
            "Neutral": 0,
            "Disagree": -1,
            "Strongly Disagree": -2
        }
    },
    {
        "category": 0,
        "question": "Should the state impose high taxes on the wealthy to support social programs?",
        "responses": {
            "Strongly Agree": -2,
            "Agree": -1,
            "Neutral": 0,
            "Disagree": 1,
            "Strongly Disagree": 2
        }
    },
    {
        "category": 1,
        "question": "Should the state allow citizens to recall elected officials before their term ends?",
        "responses": {
            "Strongly Agree": 2,
            "Agree": 1,
            "Neutral": 0,
            "Disagree": -1,
            "Strongly Disagree": -2
        }
    },
    {
        "category": 0,
        "question": "Should the state own and manage all natural resources?",
        "responses": {
            "Strongly Agree": -2,
            "Agree": -1,
            "Neutral": 0,
            "Disagree": 1,
            "Strongly Disagree": 2
        }
    },
    {
        "category": 1,
        "question": "Should the state use surveillance to monitor potential criminal activity?",
        "responses": {
            "Strongly Agree": -2,
            "Agree": -1,
            "Neutral": 0,
            "Disagree": 1,
            "Strongly Disagree": 2
        }
    },
    {
        "category": 0,
        "question": "Should the state intervene to prevent monopolies and promote competition?",
        "responses": {
            "Strongly Agree": 2,
            "Agree": 1,
            "Neutral": 0,
            "Disagree": -1,
            "Strongly Disagree": -2
        }
    },
    {
        "category": 1,
        "question": "Should the state protect freedom of speech, even if it might be offensive to some?",
        "responses": {
            "Strongly Agree": 2,
            "Agree": 1,
            "Neutral": 0,
            "Disagree": -1,
            "Strongly Disagree": -2
        }
    },
    {
        "category": 0,
        "question": "Should the state fund scientific research and development?",
        "responses": {
            "Strongly Agree": -2,
            "Agree": -1,
            "Neutral": 0,
            "Disagree": 1,
            "Strongly Disagree": 2
        }
    },
    {
        "category": 1,
        "question": "Should the state regulate the content of educational curricula?",
        "responses": {
            "Strongly Agree": -2,
            "Agree": -1,
            "Neutral": 0,
            "Disagree": 1,
            "Strongly Disagree": 2
        }
    },
    {
        "category": 0,
        "question": "Should the state control the banking and financial sector?",
        "responses": {
            "Strongly Agree": -2,
            "Agree": -1,
            "Neutral": 0,
            "Disagree": 1,
            "Strongly Disagree": 2
        }
    },
    {
        "category": 1,
        "question": "Should the state enforce mandatory military or civil service?",
        "responses": {
            "Strongly Agree": -2,
            "Agree": -1,
            "Neutral": 0,
            "Disagree": 1,
            "Strongly Disagree": 2
        }
    },
    {
        "category": 0,
        "question": "Should the state provide unemployment benefits to those who lose their jobs?",
        "responses": {
            "Strongly Agree": -2,
            "Agree": -1,
            "Neutral": 0,
            "Disagree": 1,
            "Strongly Disagree": 2
        }
    },
    {
        "category": 1,
        "question": "Should the state have the power to censor art and literature?",
        "responses": {
            "Strongly Agree": -2,
            "Agree": -1,
            "Neutral": 0,
            "Disagree": 1,
            "Strongly Disagree": 2
        }
    },
    {
        "category": 0,
        "question": "Should the state guarantee a minimum wage for all workers?",
        "responses": {
            "Strongly Agree": -2,
            "Agree": -1,
            "Neutral": 0,
            "Disagree": 1,
            "Strongly Disagree": 2
        }
    },
    {
        "category": 1,
        "question": "Should the state allow citizens to initiate and vote on legislation through referendums?",
        "responses": {
            "Strongly Agree": 2,
            "Agree": 1,
            "Neutral": 0,
            "Disagree": -1,
            "Strongly Disagree": -2
        }
    },
    {
        "category": 0,
        "question": "Should the state provide pensions for the elderly?",
        "responses": {
            "Strongly Agree": -2,
            "Agree": -1,
            "Neutral": 0,
            "Disagree": 1,
            "Strongly Disagree": 2
        }
    },
    {
        "category": 1,
        "question": "Should the state ensure the separation of powers among different branches of government?",
        "responses": {
            "Strongly Agree": 2,
            "Agree": 1,
            "Neutral": 0,
            "Disagree": -1,
            "Strongly Disagree": -2
        }
    },
    {
        "category": 0,
        "question": "Should the state subsidize renewable energy sources to combat climate change?",
        "responses": {
            "Strongly Agree": -2,
            "Agree": -1,
            "Neutral": 0,
            "Disagree": 1,
            "Strongly Disagree": 2
        }
    },
    {
        "category": 1,
        "question": "Should the state guarantee the right to protest and strike?",
        "responses": {
            "Strongly Agree": 2,
            "Agree": 1,
            "Neutral": 0,
            "Disagree": -1,
            "Strongly Disagree": -2
        }
    },
    {
        "category": 0,
        "question": "Should the state impose tariffs to protect domestic industries?",
        "responses": {
            "Strongly Agree": 2,
            "Agree": 1,
            "Neutral": 0,
            "Disagree": -1,
            "Strongly Disagree": -2
        }
    },
    {
        "category": 1,
        "question": "Should the state provide legal aid for those who cannot afford it?",
        "responses": {
            "Strongly Agree": 2,
            "Agree": 1,
            "Neutral": 0,
            "Disagree": -1,
            "Strongly Disagree": -2
        }
    },
    {
        "category": 0,
        "question": "Should the state provide free public transportation?",
        "responses": {
            "Strongly Agree": -2,
            "Agree": -1,
            "Neutral": 0,
            "Disagree": 1,
            "Strongly Disagree": 2
        }
    },
    {
        "category": 1,
        "question": "Should the state ensure equal rights and protections for all, regardless of race, religion, gender, or sexual orientation?",
        "responses": {
            "Strongly Agree": 2,
            "Agree": 1,
            "Neutral": 0,
            "Disagree": -1,
            "Strongly Disagree": -2
        }
    },
    {
        "category": 0,
        "question": "Should the state provide housing for those who cannot afford it?",
        "responses": {
            "Strongly Agree": -2,
            "Agree": -1,
            "Neutral": 0,
            "Disagree": 1,
            "Strongly Disagree": 2
        }
    },
    {
        "category": 1,
        "question": "Should the state allow non-citizens who live and work in the country to vote?",
        "responses": {
            "Strongly Agree": 2,
            "Agree": 1,
            "Neutral": 0,
            "Disagree": -1,
            "Strongly Disagree": -2
        }
    }
]

user_responses_economic_policy = 0
user_responses_governance_policy = 0

for question_dict in questions:
    question = question_dict["question"]
    st.markdown(f'**{question}**')
    options = ['Choose', 'Strongly Agree', 'Agree', 'Neutral', 'Disagree', 'Strongly Disagree']
    response = st.selectbox(
        "", 
        options, 
        key=f'{question}_response'
    )

for _ in range(3):
    st.markdown('##')

if st.button('Show Results'):
    if check_if_everything_selected() == False:
        st.error('Please answer all questions')
        st.stop()
    user_responses_economic_policy, user_responses_governance_policy = calculate_scores()
    fig, ax = plt.subplots()
    ax.set_xlim(-40, 40)
    ax.set_ylim(-40, 40)
    ax.axhline(0, color='black',linewidth=0.5)
    ax.axvline(0, color='black',linewidth=0.5)
    ax.plot(user_responses_economic_policy, user_responses_governance_policy, 'bo')
    ax.set_xticks([])
    ax.set_yticks([])
    ax.text(-40, 0, 'Autocracy', fontsize=12, verticalalignment='center', horizontalalignment='left')
    ax.text(40, 0, 'Democracy', fontsize=12, verticalalignment='center', horizontalalignment='right')
    ax.text(0, -40, 'Communism', fontsize=12, verticalalignment='bottom', horizontalalignment='center')
    ax.text(0, 40, 'Capitalism', fontsize=12, verticalalignment='top', horizontalalignment='center')
    st.pyplot(fig)


